services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HEARTBEAT: 600
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: .                     # Build from Dockerfile in the current directory
    volumes:
      - .:/usr/src/app            # Mount the local directory to the container's /usr/src/app
    ports:
      - "5000:5000"               # Expose port 5000 for Flask
    environment:
      RABBITMQ_HOST: rabbitmq     # Set RabbitMQ host environment variable
    depends_on:
      rabbitmq:
        condition: service_healthy
